### ISSUE TITLE
Wrong pip requirement pkg-resources==0.0.0

### ISSUE THREAD

**Issue by alvaromlg** [guptachetan1997/Episodes#7]
Pip req file has a wrong requirement called pkg-resources==0.0.0

https://github.com/guptachetan1997/Episodes/blob/master/requirements.txt#L8

Maybe is caused by this ubuntu pip issue? https://github.com/pypa/pip/issues/4022

**Comment by guptachetan1997** [comment]
So should I remove the pkg-resources from the requirements file? Because all I did was pip freeze.

**Comment by alvaromlg** [comment]
Yes, the error is with the pip freeze not showing correctly the requirements 
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463

**Comment by guptachetan1997** [comment]
I have edited the requirements file.
