### ISSUE TITLE
Home page not displaying all shows

### ISSUE THREAD

**Issue by EntilZha** [guptachetan1997/Episodes#8]
I added a number of shows and marked things as watched/not watched. It looks like the homepage and the all page don't show the same thing, and the homepage doesn't show that there are some upcoming shows.

On a related note:
1. How does the app decide to show things on the homepage?
2. What does the progress bar indicate (percent episodes or time to next episode)?

### Home page
<img width="1437" alt="screen shot 2017-02-13 at 9 39 57 am" src="https://cloud.githubusercontent.com/assets/1382460/22892622/7b2733de-f1d0-11e6-82ff-0977e732a640.png">

### All page
<img width="1439" alt="screen shot 2017-02-13 at 9 40 05 am" src="https://cloud.githubusercontent.com/assets/1382460/22892623/7b3ce152-f1d0-11e6-89e0-7a485a43eb86.png">

**Comment by guptachetan1997** [comment]
The home page will only display the shows that have unwatched episodes ie episodes that have aired but you have not seen them.
The all page displays all the shows.
This is helpful when you keep track of many number of shows.

**Comment by guptachetan1997** [comment]
The progress bar shows percentage episodes watched.
Green means all episodes are watched till now
Blue shows there exist unwatched aired episodes

**Comment by EntilZha** [comment]
Hmm, it's weird that House of Cards/Daredevil would show. Those haven't aired/become available on netflix yet.

**Comment by EntilZha** [comment]
Nevermind, I thought I had marked all the things I had watched as watched (I didn't, said 2016, not 2017)
